### ISSUE TITLE
Not working with the latest version of the Angular CLI and typescript

### ISSUE THREAD

**Issue by andonyns** [stokingerl/ng2-sticky-nav#5]
ERROR in ./node_modules/ng2-sticky-nav/index.ts
Module build failed: Error: C:\..\node_modules\ng2-sticky-nav\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Aluminyze\Source\aluminyze-static\Aluminyze.Static\Scripts\azWebApp\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:677:23)
    at plugin.done.then (C:\Aluminyze\Source\aluminyze-static\Aluminyze.Static\Scripts\azWebApp\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/ng2-sticky-nav/src/sticky-nav.directive.ts

**Comment by willyboy** [comment]
Please reopen if still seeing the issue.
